### ISSUE TITLE
will it work with M5Stack ?

### ISSUE THREAD

**Issue by chrissunny94** [m5stack/M5-RoverC#1]
I dont have a m5stickc , i was wondering if i can make it work with a m5stack instead .

**Comment by TinyuZhao** [comment]
In theory, there should be no problem, you can try it out. 
There are no plans to adapt to M5Stack, because the HAT interface is designed for the Stick series.

**Comment by chrissunny94** [comment]
Okay , thank you for the reply @Tinyu-Zhao  . I bought a M5Stickc in the mean time , happily playing with the bot . Thank you .

https://www.youtube.com/watch?v=am3DPjnETjs
